import * as humaneRegular from './src/fonts/humane/Humane-Regular.module.css'
import * as humaneSemiBold from './src/fonts/humane/Humane-SemiBold.module.css'
import * as humaneLight from './src/fonts/humane/Humane-Light.module.css'
import * as nohemiRegular from './src/fonts/nohemi/Nohemi-Regular.module.css'
import * as index from './src/pages/index.module.css'
